### ISSUE TITLE
Using recordings from `calibrate_and_record.py`

### ISSUE THREAD

**Issue by ajdroid** [ddetommaso/TobiiGlassesPyController-examples#1]
Hi, thanks for your work with this controller! Do you have a utility for viewing and working with the segments recorded using `calibrate_and_record.py`? Specifically, it seems that the video and gaze data are stored separately, so do you have a utility for syncing/visualizing gaze onto the video?

**Comment by ddetommaso** [comment]
Hi @ajdroid,

yes I wrote some scripts for mapping video and gaze and for exporting recordings in csv files.
Please chek out https://github.com/ddetommaso/TobiiGlassesPySuite

**Comment by ajdroid** [comment]
Thanks!
