### ISSUE TITLE
Recuperare Gaze data durante live

### ISSUE THREAD

**Issue by AlessioCasolaro** [ddetommaso/TobiiGlassesPyController-examples#3]
Ciao, ho visto il lavoro che hai svolto con il controller, ma non riesco a capire se io volessi utilizzare il protocollo RTSP per la live di Tobii, come ottengo poi i Gaze data?

Grazie in anticipo

**Comment by ddetommaso** [comment]
Ciao @AlessioCasolaro 

il video e i dati oculari viaggiano su due streaming diversi. Con RTSP puoi accedere solo al video della camera frontale, come mostrato in questo [esempio](https://github.com/ddetommaso/TobiiGlassesPyController-examples/blob/master/live_scene.py).

Tutto ciò che riguarda i dati oculari lo puoi recuperare usando il controller come in questo [esempio](https://github.com/ddetommaso/TobiiGlassesPyController-examples/blob/master/streaming.py).

Mentre se vuoi combinare i due tipi di informazioni bisogna operare una sincronizzazione opportuna (su cui ancora stiamo lavorando e che rimane al momento irrisolta, vedi questa [issue](https://github.com/ddetommaso/TobiiGlassesPyController/issues/10). Un tentativo di sincronizzazione lo trovi in questo [esempio](https://github.com/ddetommaso/TobiiGlassesPyController-examples/blob/master/live_scene_and_gaze_nocalib.py).

**Comment by AlessioCasolaro** [comment]
@ddetommaso Grazie per l'aiuto che mi stai dando, non capisco il funzionamento della get_data come potrei replicarla senza usare il controller?

**Comment by AlessioCasolaro** [comment]
Sai per caso se c'è un modo con HTTP request di recuperare questi dati? Il Doc delle API di Tobii purtroppo non mi aiuta

**Comment by ddetommaso** [comment]
@AlessioCasolaro i dati oculari sono restituiti codificati in oggetti JSON che puoi ricevere tramite socket. All'interno delle API dovresti trovare degli esempi python che ti permettono di comprenderne meglio il funzionamento. Non mi sembra che si possano prendere i dati oculari con richieste HTTP.
